vcomp: add missing "stdlib.h" include
Newer compilers are stricter, this change should fix the following
compilation error:

    In file included from ../../../../libqemu-src/subprojects/virclrenderer/src/vcl/vcomp_cl_context.h:9,
                     from ../../../../libqemu-src/subprojects/virclrenderer/src/vcl/vcomp_context.c:7:
    ../../../../libqemu-src/subprojects/virclrenderer/src/vcl/vcomp_common.h: In function ‘vcomp_object_alloc’:
    ../../../../libqemu-src/subprojects/virclrenderer/src/vcl/vcomp_common.h:57:31: error: implicit declaration of function ‘calloc’ [-Werror=implicit-function-declaration]
       57 |    struct vcomp_object *obj = calloc(1, size);
          |                               ^~~~~~

Signed-off-by: Brian Cain <bcain@quicinc.com>