vrend: fix building on Android
Building vrend_renderer.c fails on Android with the following message
because of a partial initializer detected by
`-Wmissing-field-initializers`:

-----------------------------------------------------------------------
external/virglrenderer/src/vrend_renderer.c:1230:48: error: missing field 'alloc_size' initializer [-Werror,-Wmissing-field-initializers]
   struct vrend_strbuf logger_buffer = { NULL, };
-----------------------------------------------------------------------

Using an empty initializer like {} would have fixed the issue, but then
an another error would have come up:

-----------------------------------------------------------------------
external/virglrenderer/src/vrend_renderer.c:1230:40: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
   struct vrend_strbuf logger_buffer = {};

-----------------------------------------------------------------------

Use an aggregate initializer instead which has the equivalent effect of
setting the first field to NULL, but it does not cause problems with
`-Wmissing-field-initializers` or `-Werror,-Wgnu-empty-initializer`.

Part-of: <https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/1430>