vrend: fix compile failure on legacy map info query
../src/vrend/vrend_winsys_gbm.c: In function ‘virgl_gbm_get_map_info’:
../src/vrend/vrend_winsys_gbm.c:555:44: error: ‘gbm’ undeclared (first use in this function)
  555 |    if (!strcmp(gbm_device_get_backend_name(gbm->device), "i915"))

Fixes: 2fcee2ef ("vrend: conditionally build using gbm_bo_get_map_info()")
Part-of: <https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/1519>